[build]
  publish = "."
  command = ""

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "no-cache"
